name: Enmpoy 7/24 Ölüm Makinesi

# Ne zaman tetiklenecek?
on:
  schedule:
    # Sistemi 4 saatte bir ateşler. Limitlere takılmadan aralıksız sömürür.
    - cron: "0 */4 * * *"
  workflow_dispatch: # Actions sekmesinden "Run workflow" diyerek elle tetikleyebilmeni sağlar

jobs:
  anigexis_somurucu:
    runs-on: ubuntu-latest # GitHub'ın beleş ve hızlı makinesine çöküyoruz

    steps:
      - name: Depoyu Çek
        uses: actions/checkout@v3

      - name: Python 3.10 Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Silahları ve Şarjörleri Yükle (Stealth Zırhı Dahil!)
        run: |
          python -m pip install --upgrade pip
          # İŞTE KRİTİK NOKTA: playwright-stealth buraya eklendi, artık o amcık sunucu hata vermeyecek!
          pip install playwright yt-dlp huggingface_hub playwright-stealth
          playwright install chromium --with-deps

      - name: Motoru Ateşle ve İçinden Geç!
        run: |
          python bot.py
